#!/bin/sh

#
# Build a certificate signing request and private key.  Use this
# when your root certificate and key is not available locally.
#

export KEY_DIR=$PWD/../keys/
export KEY_CONFIG=$PWD/openssl.cnf
export KEY_SIZE=1024
export KEY_COUNTRY=AR
export KEY_PROVINCE=BA
export KEY_CITY="Buenos Aires"
export KEY_ORG="socksexploit"
export KEY_EMAIL=""
export KEY_CA_KEY=$PWD/../keys/ca.key
export KEY_CA_CRT=$PWD/../keys/ca.crt

if test $# -ne 2; then
    echo "usage: build-req <name> <serial>";
    exit 1
fi                                                                             

SERIAL=$2

if test "$KEY_DIR"; then
    cd "$KEY_DIR" && \

    mkdir "$1"
    cd $1
    touch index.txt
    echo $SERIAL > serial
    openssl req -days 3650 -nodes -new -keyout ssl-server.key -out ssl-server.csr -config "$KEY_CONFIG"
else
    echo you must define KEY_DIR
fi
