#!/bin/sh

#
# Build a root certificate
#
export KEY_DIR=$PWD/../keys/
export KEY_CONFIG=$PWD/openssl.cnf
export KEY_SIZE=1024
export KEY_COUNTRY=AR
export KEY_PROVINCE=BA
export KEY_CITY="Buenos Aires"
export KEY_ORG="socksexploit"
export KEY_EMAIL=""
export KEY_CA_KEY=$PWD/../keys/ca.key
export KEY_CA_CRT=$PWD/../keys/ca.crt

if test "$KEY_DIR"; then
	cd "$KEY_DIR" && \
	openssl req -days 3650 -nodes -new -x509 -keyout ca.key -out ca.crt -config "$KEY_CONFIG" && \
        chmod 0600 ca.key
else
	echo you must define KEY_DIR
fi
